DB_HOST: "localhost"
DB_PORT: "5432"
DB_DATABASE: "postgres"
DB_USER: "postgres"
DB_PASSWORD: "zabimaru1"
# mrpanel-server/src/main/resources/application.yml
# This file is used to configure the Spring application properties for mrpanel-server.
# It includes database connection settings and Flyway migration configurations.

spring:
  application:
    name: "mrpanel-server"
  datasource:
    url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}"
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: "org.postgresql.Driver"
  flyway:
    url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}"
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: "org.postgresql.Driver"
    locations: "classpath:db/migration"