import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.scss";

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin", "latin-ext"],
  weight: ["300", "400", "100", "700", "900"],
});


export const metadata: Metadata = {
  title: "MR Panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.className}`}>
        {children}
      </body>
    </html>
  );
}
