import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.scss";
import React, { Suspense } from "react";
import Spinner from "@/components/loader/Spinner";
import Providers from "@/components/SignInButton/Providers";
import DigBar from "@/components/DigBar/DigBar";
const lato = Lato({
    variable: "--font-lato",
    subsets: ["latin", "latin-ext"],
    weight: ["300", "400", "100", "700", "900"],
});


export const metadata: Metadata = {
    title: "MR Panel",
    description: "Generated by create next app",
};

const Loading = () => <div style={{
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: '100%'
}}><Spinner/></div>;

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${lato.className}`}>
                <Suspense fallback={<Loading/>}>
                    <Providers>
                        <DigBar/>
                        {children}</Providers>
                </Suspense>
            </body>
        </html>
    );
}
