name: CI/CD
on:
  push:
    branches:
      - master
      - develop
  merge_group:
    types:
      - checks_requested
jobs:
  compileAndTest:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: temurin
          architecture: x64
          cache: maven
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify

